# .github/workflows/main.yml
name: Main Checks 

on:
  push:
    branches: [ "main" ]

jobs:
  dummy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dummy Test
        run: echo "Production is live 🎉"
