# .github/workflows/pr-checks.yml
name: PR Checks 

on:
  pull_request:
    branches: [ "staging" ]

jobs:
  dummy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dummy HTML Test
        run: echo "HTML looks good ✅"

