# .github/workflows/staging.yml
name: Staging E2E

on:
  push:
    branches: [ "staging" ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Run E2E tests
        run: npm run test:e2e
