# .github/workflows/staging.yml
name: Staging Checks 

on:
  push:
    branches: [ "staging" ]

jobs:
  dummy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Dummy Test
        run: echo "Staging passed 🚀"

